# Generated by Django 3.1.1 on 2020-10-02 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200925_0134'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
