# Generated by Django 3.1.1 on 2020-10-05 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myapp', '0003_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=30)),
                ('date', models.DateTimeField()),
                ('attendants', models.IntegerField()),
                ('invited', models.IntegerField()),
            ],
        ),
    ]
