# Generated by Django 3.1.1 on 2020-12-01 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_question_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='resultID',
            field=models.IntegerField(default=0),
        ),
    ]
