# Generated by Django 3.1.1 on 2020-12-02 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_question_resultid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choiceResult', to='myapp.choice'),
        ),
    ]
