# Generated by Django 3.1.1 on 2020-12-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_auto_20201202_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='result',
            field=models.CharField(default='', max_length=30),
        ),
    ]
