# Generated by Django 3.1.1 on 2020-11-17 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_auto_20201021_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='tripId',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='myapp.event'),
        ),
        migrations.AlterField(
            model_name='question',
            name='pub_date',
            field=models.DateTimeField(verbose_name='Date Published'),
        ),
    ]
