# Generated by Django 3.1.1 on 2020-11-17 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_auto_20201117_0655'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='category',
            field=models.CharField(default='', max_length=30),
        ),
    ]
